apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: "hacbs-signing-pipeline"
    app: "hacbs-signing-pipeline"
    env: production
    paas.redhat.com/appcode: RSIG-001
    test: scottp
  name: "hacbs-signing-pipeline-config"
data:
  PYXIS_URL: "https://pyxis.engineering.redhat.com"
  SIG_KEY_ID: "<TBD>"
  SIG_KEY_NAME: "<TBD>"
  SSL_CERT_FILE_NAME: "hacbs-signing-pipeline.pem"
  SSL_CERT_SECRET_NAME: "hacbs-signing-pipeline-certs"
  SSL_KEY_FILE_NAME: "hacbs-signing-pipeline.key"
  UMB_CLIENT_NAME: "hacbs-signing-pipeline"
  UMB_URL: "umb.api.redhat.com"
  UMB_LISTEN_TOPIC: VirtualTopic.eng.robosignatory.hacbs.sign
  UMB_PUBLISH_TOPIC: VirtualTopic.eng.hacbs-signing-pipeline.hacbs.sign
